wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1699507514.359136
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.9.12
      5: 0.13.3
      8:
      - 3
      - 5
adam:
  desc: null
  value: false
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 2
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
cfg:
  desc: null
  value: models/yolov5s.yaml
data:
  desc: null
  value: data\yolov5obb_demo.yaml
data_dict:
  desc: null
  value:
    names:
    - defective_insulator
    - broken_defect
    - good_insulator
    - flashover_defect
    nc: 4
    path: dataset
    test: dataset\test.txt
    train: dataset\train.txt
    val: dataset\val.txt
device:
  desc: null
  value: '0'
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 500
evolve:
  desc: null
  value: null
exist_ok:
  desc: null
  value: false
freeze:
  desc: null
  value:
  - 0
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    cls_theta: 180
    copy_paste: 0.0
    csl_radius: 2.0
    degrees: 180.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.5
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.2
    mixup: 0.1
    momentum: 0.937
    mosaic: 0.75
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.25
    shear: 0.0
    theta: 0.5
    theta_pw: 1.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
imgsz:
  desc: null
  value: 512
label_smoothing:
  desc: null
  value: 0.0
linear_lr:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: exp
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
patience:
  desc: null
  value: 100
project:
  desc: null
  value: runs\train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs\train\exp17
save_period:
  desc: null
  value: -1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: yolov5s.pt
workers:
  desc: null
  value: 2
